config/routes.rb
Ticketee::Application.routes.draw do
  root to: "projects#index"

  default_url_options host: "mysite.com"

  devise_for :users, controllers: { registrations: "registrations" }
  get '/awaiting_confirmation',
      to: "users#confirmation",
      as: 'confirm_user'

  resources :projects do
    resources :tickets
  end

  namespace :admin do
    root to: "base#index"
    resources :users do
      resources :permissions
    end
  end

  put '/admin/users/:user_id/permissions',
      :to => 'admin/permissions#update',
      :as => :update_user_permissions

end

app/models/project.rb
class Project < ActiveRecord::Base
    has_many :tickets
    
    validates :name, presence: true, uniqueness: true

    has_many :permissions, :as => :thing

    scope :readable_by, lambda { |user|
        joins(:permissions).where(permissions: { action: "view", user_id: user.id })
    }

    def self.for(user)
        user.admin? ? Project : Project.readable_by(user)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authorize_admin!, except: [:index, :show]
  before_filter :authenticate_user!, only: [:index, :show]
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.for(current_user).all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    if @project.save
      flash[:notice] = "Project has been created."
      redirect_to @project
    else
      flash[:alert] = "Project has not been created."
      render action: "new"
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    if @project.update_attributes(project_params)
      flash[:notice] = "Project has been updated."
      redirect_to @project
    else
      flash[:alert] = "Project has not been updated."
      render :action => "edit"
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    flash[:notice] = "Project has been deleted."
    redirect_to projects_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.for(current_user).find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The project you were looking for could not be found."
      redirect_to projects_path
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= form_for(@project) do |f|
  - if @project.errors.any?
    #error_explanation
      %h2
        = pluralize(@project.errors.count, "error")
        prohibited this project from being saved:
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .actions
    = f.submit

app/views/projects/edit.html.haml
%h2 Edit project
= render "form"

app/views/projects/index.html.haml
= admins_only do
  = link_to "New Project", new_project_path
%h2 Projects
%ul
  - @projects.each do |project|
    %li= link_to project.name, project

app/views/projects/new.html.haml
%h2 New project
= render "form"

app/views/projects/show.html.haml
- title(@project.name, "Projects")
%h2= @project.name
= admins_only do
  = link_to "Edit Project", edit_project_path(@project)
  = link_to "Delete Project", @project, method: :delete,     |
    confirm: "Are you sure you want to delete this project?" |
= authorized?("create tickets".to_sym, @project) do
  = link_to "New Ticket", new_project_ticket_path(@project)
%ul#tickets
  - @project.tickets.each do |ticket|
    %li
      \##{ticket.id} - #{link_to ticket.title, [@project, ticket]}